version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db #db dir
    restart: always
  yapi:
    image: icymind/yapi
    container_name: yapi
    ports:
      - 8001:3000
    depends_on:
      - mongo
    command: node server/app.js
    restart: always
volumes:
    mongo-data:
      external: true
